version: "3.9"

services:
  mysql-user:
    image: mysql:8.0
    container_name: mysql_user
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: user_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_user_data:/var/lib/mysql
 
  user-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: user_service
    ports:
      - "8080:8080"
    depends_on:
      - mysql-user

volumes:
  mysql_user_data: